# ðŸŸ¦ Redirection SPA Flutter Web
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# ðŸŸ§ Configuration du build Netlify
[build]
  publish = "build/web"
  command = "sh ./netlify_build.sh"

[build.environment]
  FLUTTER_VERSION = "3.24.0"
